// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySkillTest.Persistence.Data;

#nullable disable

namespace MySkillTest.Persistence.Data.Migrations
{
    [DbContext(typeof(MySkillTestDbContext))]
    partial class MySkillTestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MySkillTest.Domain.Domain.RegisteredCompany", b =>
                {
                    b.Property<Guid>("RegisteredCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RegisteredCompanyId");

                    b.ToTable("RegisteredCompanies", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnswerOrder")
                        .HasColumnType("int");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AllowPausing")
                        .HasColumnType("bit");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AttemptsAllowed")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFreezed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsProctorRequired")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("RandomizeQuestions")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReadQuestionsFromAssessment")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SecondaryClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeLimitInMinutes")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SecondaryClientId");

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDetail", b =>
                {
                    b.Property<Guid>("AssessmentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentDomainDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplexityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NoOfCodingQuestions")
                        .HasColumnType("int");

                    b.Property<int>("NoOfQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("TimeLimitInMinutes")
                        .HasColumnType("int");

                    b.HasKey("AssessmentDetailId");

                    b.HasIndex("AssessmentDomainDomainId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ComplexityId");

                    b.ToTable("AssessmentDetails");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomain", b =>
                {
                    b.Property<Guid>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompilerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DomainShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PrimaryDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DomainId");

                    b.HasIndex("CompilerId");

                    b.HasIndex("PrimaryDomainId");

                    b.ToTable("AssessmentDomain", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomainLimitTracker", b =>
                {
                    b.Property<Guid>("AssessmentDomainLimitTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentDomainDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AssessmentDomainLimit")
                        .HasColumnType("int");

                    b.Property<Guid>("ComplexityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("QuestionsPresentedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssessmentDomainLimitTrackerId");

                    b.HasIndex("AssessmentDomainDomainId");

                    b.HasIndex("ComplexityId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("AssessmentDomainLimitTrackers");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentLibrary", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("LibraryId");

                    b.HasIndex("DomainId");

                    b.ToTable("AssessmentLibrary", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("AssessmentQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssessmentOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssessmentQuestionId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AssessmentQuestions");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoweredApplicationUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.ClientLogo", b =>
                {
                    b.Property<Guid>("ClientLogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ClientLogoContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("ClientLogoGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ClientLogoId");

                    b.ToTable("ClientLogoes");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Compiler", b =>
                {
                    b.Property<Guid>("CompilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompilerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompilerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MonacoEditorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompilerId");

                    b.ToTable("Compilers");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Complexity", b =>
                {
                    b.Property<Guid>("ComplexityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexityLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ComplexityId");

                    b.ToTable("Complexities");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReport", b =>
                {
                    b.Property<Guid>("EvidenceReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Screen_recording_url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Screen_recording_url");

                    b.Property<string>("StartedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_taker_photo_url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Test_taker_photo_url");

                    b.Property<int?>("TrustScore")
                        .HasColumnType("int");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EvidenceReportId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("EvidenceReports");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReportDetail", b =>
                {
                    b.Property<Guid>("EvidenceReportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EvidenceReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Evidence_iso_datetime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Evidence_iso_datetime");

                    b.Property<string>("Evidence_label")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Evidence_label");

                    b.Property<string>("Evidence_url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Evidence_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("Is_violation")
                        .HasColumnType("bit")
                        .HasColumnName("Is_violation");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EvidenceReportDetailId");

                    b.HasIndex("EvidenceReportId");

                    b.ToTable("EvidenceReportDetails");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.LibraryQuestion", b =>
                {
                    b.Property<Guid>("LibraryQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssessmentOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LibraryQuestionId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("QuestionId");

                    b.ToTable("LibraryQuestions");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.PrimaryDomain", b =>
                {
                    b.Property<Guid>("PrimaryDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PrimaryDomainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PrimaryDomainShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PrimaryDomainId");

                    b.ToTable("PrimaryDomains");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.ProctoringResult", b =>
                {
                    b.Property<Guid>("ProctoringResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AveragesB1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesB2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesB3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesK1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesM1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesM2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesN1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesN2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesS1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesS2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoppedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProctoringResultId");

                    b.ToTable("ProctoringResults");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplexityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("QuestionTextFormatted")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QuestionUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionId");

                    b.HasIndex("ComplexityId");

                    b.HasIndex("DomainId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.QuestionType", b =>
                {
                    b.Property<Guid>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AllowMultipleSelection")
                        .HasColumnType("bit");

                    b.Property<bool?>("Coding")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("MultipleChoice")
                        .HasColumnType("bit");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TypeId");

                    b.ToTable("QuestionType", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Client1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Client2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoweredRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.HasIndex("Client1Id");

                    b.HasIndex("Client2Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessment", b =>
                {
                    b.Property<Guid>("UserAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Attempts")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("RunningScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("SecondaryAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecondaryClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("StartDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StatusUpdateDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("StatusUpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("TimeRemainingInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.Property<Guid>("UserAssessmentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssessmentId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SecondaryAssessmentId");

                    b.HasIndex("SecondaryClientId");

                    b.HasIndex("UserAssessmentStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssessments", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentEvidenceDetail", b =>
                {
                    b.Property<Guid>("UserAssessmentEvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HashedTestAttemptId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TestAttemptId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssessmentEvidenceId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserAssessmentEvidenceDetail", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentFile", b =>
                {
                    b.Property<Guid>("UserAssessmentFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssessmentFileId");

                    b.ToTable("UserAssessmentFiles");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentIAI", b =>
                {
                    b.Property<Guid>("UserAssessmentIAIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserIdIAI")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssessmentIAIId");

                    b.HasIndex("UserAssessmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssessmentIAI", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentPanel", b =>
                {
                    b.Property<Guid>("UserAssessmentPanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssessmentPanelId");

                    b.HasIndex("UserAssessmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssessmentPanel", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentProctorResult", b =>
                {
                    b.Property<Guid>("UserAssessmentProctorResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("PDFContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ResultContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssessmentProctorResultId");

                    b.ToTable("UserAssessmentProctorResults");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentStatu", b =>
                {
                    b.Property<Guid>("UserAssessmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserAssessmentStatusName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserAssessmentStatusId");

                    b.ToTable("UserAssessmentStatu", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentTracker", b =>
                {
                    b.Property<Guid>("UserAssessmentTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Presented")
                        .HasColumnType("bit");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssessmentTrackerId");

                    b.HasIndex("DomainId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserAssessmentTrackers");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserMaster", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("FailedPasswordAttemptCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastActivityDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastLockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastLoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastPasswordChangedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoweredUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MobileNo")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasswordFormat")
                        .HasColumnType("int");

                    b.Property<bool>("PasswordResetRequestActive")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("ClientId");

                    b.ToTable("UserMasters", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponse", b =>
                {
                    b.Property<Guid>("UserResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserResponseId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("ClientId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserResponse", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponseFreeTextAnswer", b =>
                {
                    b.Property<Guid>("UserResponseFreeTextAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAnswerCompiled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserResponseFreeTextAnswerId");

                    b.ToTable("UserResponseFreeTextAnswers");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponseMultipleAnswer", b =>
                {
                    b.Property<Guid>("UserResponseAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PrimaryUserResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecondaryUserResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserResponseAnswerId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("PrimaryUserResponseId");

                    b.HasIndex("SecondaryUserResponseId");

                    b.ToTable("UserResponseMultipleAnswer", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Client1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("Role1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserMasterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleId");

                    b.HasIndex("Client1Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Role1Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMasterUserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Answer", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "PrimaryClient")
                        .WithMany("Assessments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Assessment_Client");

                    b.HasOne("MySkillTest.Domain.Entities.Client", "SecondaryClient")
                        .WithMany("SecondaryAssessments")
                        .HasForeignKey("SecondaryClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Assessment_Client1");

                    b.Navigation("PrimaryClient");

                    b.Navigation("SecondaryClient");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDetail", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("AssessmentDetails")
                        .HasForeignKey("AssessmentDomainDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentDetails")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Complexity", "Complexity")
                        .WithMany("AssessmentDetails")
                        .HasForeignKey("ComplexityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Complexity");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomain", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Compiler", "Compiler")
                        .WithMany("AssessmentDomains")
                        .HasForeignKey("CompilerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySkillTest.Domain.Entities.PrimaryDomain", "PrimaryDomain")
                        .WithMany("AssessmentDomains")
                        .HasForeignKey("PrimaryDomainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Compiler");

                    b.Navigation("PrimaryDomain");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomainLimitTracker", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("AssessmentDomainLimitTrackers")
                        .HasForeignKey("AssessmentDomainDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Complexity", "Complexity")
                        .WithMany("AssessmentDomainLimitTrackers")
                        .HasForeignKey("ComplexityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("AssessmentDomainLimitTrackers")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Complexity");

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentLibrary", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("AssessmentLibraries")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentLibrary_AssessmentDomain");

                    b.Navigation("AssessmentDomain");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReport", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("EvidenceReports")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReportDetail", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.EvidenceReport", "EvidenceReport")
                        .WithMany("EvidenceReportDetails")
                        .HasForeignKey("EvidenceReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvidenceReport");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.LibraryQuestion", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "Assessment")
                        .WithMany("LibraryQuestions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("LibraryQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Question", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Complexity", "Complexity")
                        .WithMany("Questions")
                        .HasForeignKey("ComplexityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("Questions")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Complexity");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Role", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client1")
                        .WithMany("Roles1")
                        .HasForeignKey("Client1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Role_Client1");

                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client2")
                        .WithMany("Roles2")
                        .HasForeignKey("Client2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Role_Client2");

                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("Roles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Role_Client");

                    b.Navigation("Client");

                    b.Navigation("Client1");

                    b.Navigation("Client2");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessment", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "PrimaryAssessment")
                        .WithMany("UserAssessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserAssessment_Assessment");

                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserAssessments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserAssessment_Client");

                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "SecondaryAssessment")
                        .WithMany("SecondaryUserAssessments")
                        .HasForeignKey("SecondaryAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_UserAssessment_Assessment1");

                    b.HasOne("MySkillTest.Domain.Entities.Client", "SecondaryClient")
                        .WithMany("SecondaryUserAssessments")
                        .HasForeignKey("SecondaryClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_UserAssessment_Client1");

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessmentStatu", "UserAssessmentStatu")
                        .WithMany("UserAssessments")
                        .HasForeignKey("UserAssessmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserAssessment_UserAssessmentStatu");

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany("UserAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PrimaryAssessment");

                    b.Navigation("SecondaryAssessment");

                    b.Navigation("SecondaryClient");

                    b.Navigation("UserAssessmentStatu");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentEvidenceDetail", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentEvidenceDetails")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentIAI", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentIAIs")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany("UserAssessmentIAIs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentPanel", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentPanels")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany("UserAssessmentPanels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentTracker", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("UserAssessmentTrackers")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("UserAssessmentTrackers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentTrackers")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Question");

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserMaster", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserMasters")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponse", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Answer", "Answer")
                        .WithMany("UserResponses")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserResponses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("UserResponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserResponses")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Client");

                    b.Navigation("Question");

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponseMultipleAnswer", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Answer", "Answer")
                        .WithMany("UserResponseMultipleAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserResponse", "PrimaryUserResponse")
                        .WithMany("PrimaryMultipleAnswers")
                        .HasForeignKey("PrimaryUserResponseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MySkillTest.Domain.Entities.UserResponse", "SecondaryUserResponse")
                        .WithMany("SecondaryMultipleAnswers")
                        .HasForeignKey("SecondaryUserResponseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Answer");

                    b.Navigation("PrimaryUserResponse");

                    b.Navigation("SecondaryUserResponse");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client1")
                        .WithMany("UserRoles1")
                        .HasForeignKey("Client1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_UserRole_Client1");

                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserRoles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Client");

                    b.HasOne("MySkillTest.Domain.Entities.Role", "Role1")
                        .WithMany("UserRoles1")
                        .HasForeignKey("Role1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_UserRole_Role1");

                    b.HasOne("MySkillTest.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Role");

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserMasterUserId");

                    b.Navigation("Client");

                    b.Navigation("Client1");

                    b.Navigation("Role");

                    b.Navigation("Role1");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Answer", b =>
                {
                    b.Navigation("UserResponseMultipleAnswers");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentDetails");

                    b.Navigation("AssessmentQuestions");

                    b.Navigation("LibraryQuestions");

                    b.Navigation("SecondaryUserAssessments");

                    b.Navigation("UserAssessments");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomain", b =>
                {
                    b.Navigation("AssessmentDetails");

                    b.Navigation("AssessmentDomainLimitTrackers");

                    b.Navigation("AssessmentLibraries");

                    b.Navigation("Questions");

                    b.Navigation("UserAssessmentTrackers");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Client", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Roles");

                    b.Navigation("Roles1");

                    b.Navigation("Roles2");

                    b.Navigation("SecondaryAssessments");

                    b.Navigation("SecondaryUserAssessments");

                    b.Navigation("UserAssessments");

                    b.Navigation("UserMasters");

                    b.Navigation("UserResponses");

                    b.Navigation("UserRoles");

                    b.Navigation("UserRoles1");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Compiler", b =>
                {
                    b.Navigation("AssessmentDomains");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Complexity", b =>
                {
                    b.Navigation("AssessmentDetails");

                    b.Navigation("AssessmentDomainLimitTrackers");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReport", b =>
                {
                    b.Navigation("EvidenceReportDetails");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.PrimaryDomain", b =>
                {
                    b.Navigation("AssessmentDomains");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("AssessmentQuestions");

                    b.Navigation("LibraryQuestions");

                    b.Navigation("UserAssessmentTrackers");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserRoles1");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessment", b =>
                {
                    b.Navigation("AssessmentDomainLimitTrackers");

                    b.Navigation("EvidenceReports");

                    b.Navigation("UserAssessmentEvidenceDetails");

                    b.Navigation("UserAssessmentIAIs");

                    b.Navigation("UserAssessmentPanels");

                    b.Navigation("UserAssessmentTrackers");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentStatu", b =>
                {
                    b.Navigation("UserAssessments");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserMaster", b =>
                {
                    b.Navigation("UserAssessmentIAIs");

                    b.Navigation("UserAssessmentPanels");

                    b.Navigation("UserAssessments");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponse", b =>
                {
                    b.Navigation("PrimaryMultipleAnswers");

                    b.Navigation("SecondaryMultipleAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
