// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySkillTest.Persistence.Data;

#nullable disable

namespace MySkillTest.Persistence.Migrations
{
    [DbContext(typeof(MySkillTestDbContext))]
    [Migration("20251122063706_fixCascade")]
    partial class fixCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MySkillTest.Domain.Domain.RegisteredCompany", b =>
                {
                    b.Property<int>("RegisteredCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisteredCompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RegisteredCompanyId");

                    b.ToTable("RegisteredCompany");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<int?>("AnswerOrder")
                        .HasColumnType("int");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<bool?>("AllowPausing")
                        .HasColumnType("bit");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AttemptsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFreezed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsProctorRequired")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("RandomizeQuestions")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReadQuestionsFromAssessment")
                        .HasColumnType("bit");

                    b.Property<int>("TimeLimitInMinutes")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ClientId");

                    b.ToTable("Assessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDetail", b =>
                {
                    b.Property<int>("AssessmentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentDetailId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("ComplexityId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NoOfCodingQuestions")
                        .HasColumnType("int");

                    b.Property<int>("NoOfQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("TimeLimitInMinutes")
                        .HasColumnType("int");

                    b.HasKey("AssessmentDetailId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ComplexityId");

                    b.HasIndex("DomainId");

                    b.ToTable("AssessmentDetail");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomain", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomainId"));

                    b.Property<int?>("CompilerId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PrimaryDomainId")
                        .HasColumnType("int");

                    b.HasKey("DomainId");

                    b.HasIndex("CompilerId");

                    b.HasIndex("PrimaryDomainId");

                    b.ToTable("AssessmentDomain");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomainLimitTracker", b =>
                {
                    b.Property<int>("AssessmentDomainLimitTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentDomainLimitTrackerId"));

                    b.Property<int?>("AssessmentDomainLimit")
                        .HasColumnType("int");

                    b.Property<int>("ComplexityId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("QuestionsPresentedCount")
                        .HasColumnType("int");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentDomainLimitTrackerId");

                    b.HasIndex("ComplexityId");

                    b.HasIndex("DomainId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("AssessmentDomainLimitTracker");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentLibrary", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibraryId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("LibraryId");

                    b.HasIndex("DomainId");

                    b.ToTable("AssessmentLibrary");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Property<int>("AssessmentQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentQuestionId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("AssessmentOrder")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentQuestionId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AssessmentQuestion");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ApplicationUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoweredApplicationUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.ClientLogo", b =>
                {
                    b.Property<int>("ClientLogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientLogoId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ClientLogoGuid")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ClientLogoId");

                    b.ToTable("ClientLogo");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Compiler", b =>
                {
                    b.Property<int>("CompilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompilerId"));

                    b.Property<string>("CompilerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompilerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MonacoEditorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompilerId");

                    b.ToTable("Compiler");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Complexity", b =>
                {
                    b.Property<int>("ComplexityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplexityId"));

                    b.Property<string>("ComplexityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ComplexityId");

                    b.ToTable("Complexity");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReport", b =>
                {
                    b.Property<int>("EvidenceReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenceReportId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinishedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Screen_recording_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_taker_photo_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrustScore")
                        .HasColumnType("int");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("EvidenceReportId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("EvidenceReport");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReportDetail", b =>
                {
                    b.Property<int>("EvidenceReportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenceReportDetailId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EvidenceReportId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Evidence_iso_datetime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Evidence_label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidence_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("Is_violation")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EvidenceReportDetailId");

                    b.HasIndex("EvidenceReportId");

                    b.ToTable("EvidenceReportDetail");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.LibraryQuestion", b =>
                {
                    b.Property<int>("LibraryQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibraryQuestionId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("AssessmentOrder")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("LibraryQuestionId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("QuestionId");

                    b.ToTable("LibraryQuestion");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.PrimaryDomain", b =>
                {
                    b.Property<int>("PrimaryDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrimaryDomainId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PrimaryDomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryDomainShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrimaryDomainId");

                    b.ToTable("PrimaryDomain");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.ProctoringResult", b =>
                {
                    b.Property<int>("ProctoringResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProctoringResultId"));

                    b.Property<string>("AveragesB1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesB2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesB3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesC5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesK1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesM1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesM2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesN1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesN2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesS1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AveragesS2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoppedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProctoringResultId");

                    b.ToTable("ProctoringResult");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("ComplexityId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionTextFormatted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionUniqueId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("ComplexityId");

                    b.HasIndex("DomainId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.QuestionType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<bool?>("AllowMultipleSelection")
                        .HasColumnType("bit");

                    b.Property<bool?>("Coding")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("MultipleChoice")
                        .HasColumnType("bit");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("QuestionType");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoweredRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.HasIndex("ClientId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessment", b =>
                {
                    b.Property<int>("UserAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int?>("Attempts")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("RunningScore")
                        .HasColumnType("int");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StatusUpdateDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("StatusUpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("TimeRemainingInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserAssessmentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserAssessmentStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentEvidenceDetail", b =>
                {
                    b.Property<int>("UserAssessmentEvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentEvidenceId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HashedTestAttemptId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TestAttemptId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentEvidenceId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserAssessmentEvidenceDetail");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentFile", b =>
                {
                    b.Property<int>("UserAssessmentFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentFileId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentFileId");

                    b.ToTable("UserAssessmentFile");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentIAI", b =>
                {
                    b.Property<int>("UserAssessmentIAIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentIAIId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JobRequirementId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserIdIAI")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentIAIId");

                    b.HasIndex("UserAssessmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssessmentIAI");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentPanel", b =>
                {
                    b.Property<int>("UserAssessmentPanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentPanelId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PanelId")
                        .HasColumnType("int");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserMasterUserId")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentPanelId");

                    b.HasIndex("UserAssessmentId");

                    b.HasIndex("UserMasterUserId");

                    b.ToTable("UserAssessmentPanel");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentProctorResult", b =>
                {
                    b.Property<int>("UserAssessmentProctorResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentProctorResultId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("PDFContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ResultContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentProctorResultId");

                    b.ToTable("UserAssessmentProctorResult");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentStatu", b =>
                {
                    b.Property<int>("UserAssessmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentStatusId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserAssessmentStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserAssessmentStatusId");

                    b.ToTable("UserAssessmentStatu");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentTracker", b =>
                {
                    b.Property<int>("UserAssessmentTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentTrackerId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("Presented")
                        .HasColumnType("bit");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentTrackerId");

                    b.HasIndex("DomainId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserAssessmentTracker");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserMaster", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FailedPasswordAttemptCount")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastActivityDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastLockoutDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastLoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastPasswordChangedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoweredUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MobileNo")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasswordFormat")
                        .HasColumnType("int");

                    b.Property<bool>("PasswordResetRequestActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("ClientId");

                    b.ToTable("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponse", b =>
                {
                    b.Property<int>("UserResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserResponseId"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("UserResponseId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("ClientId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserResponse");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponseFreeTextAnswer", b =>
                {
                    b.Property<int>("UserResponseFreeTextAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserResponseFreeTextAnswerId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAnswerCompiled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserResponseId")
                        .HasColumnType("int");

                    b.HasKey("UserResponseFreeTextAnswerId");

                    b.ToTable("UserResponseFreeTextAnswer");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponseMultipleAnswer", b =>
                {
                    b.Property<int>("UserResponseAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserResponseAnswerId"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserResponseId")
                        .HasColumnType("int");

                    b.HasKey("UserResponseAnswerId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("UserResponseId");

                    b.ToTable("UserResponseMultipleAnswer");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Answer", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("Assessments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDetail", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentDetails")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Complexity", "Complexity")
                        .WithMany("AssessmentDetails")
                        .HasForeignKey("ComplexityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("AssessmentDetails")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Complexity");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomain", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Compiler", "Compiler")
                        .WithMany("AssessmentDomains")
                        .HasForeignKey("CompilerId");

                    b.HasOne("MySkillTest.Domain.Entities.PrimaryDomain", "PrimaryDomain")
                        .WithMany("AssessmentDomains")
                        .HasForeignKey("PrimaryDomainId");

                    b.Navigation("Compiler");

                    b.Navigation("PrimaryDomain");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomainLimitTracker", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Complexity", "Complexity")
                        .WithMany("AssessmentDomainLimitTrackers")
                        .HasForeignKey("ComplexityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("AssessmentDomainLimitTrackers")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("AssessmentDomainLimitTrackers")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Complexity");

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentLibrary", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("AssessmentLibraries")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentDomain");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReport", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("EvidenceReports")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReportDetail", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.EvidenceReport", "EvidenceReport")
                        .WithMany("EvidenceReportDetails")
                        .HasForeignKey("EvidenceReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvidenceReport");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.LibraryQuestion", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "Assessment")
                        .WithMany("LibraryQuestions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("LibraryQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Question", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Complexity", "Complexity")
                        .WithMany("Questions")
                        .HasForeignKey("ComplexityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("Questions")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Complexity");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Role", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("Roles")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessment", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Assessment", "Assessment")
                        .WithMany("UserAssessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserAssessments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessmentStatu", "UserAssessmentStatu")
                        .WithMany("UserAssessments")
                        .HasForeignKey("UserAssessmentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany("UserAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Client");

                    b.Navigation("UserAssessmentStatu");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentEvidenceDetail", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentEvidenceDetails")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentIAI", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentIAIs")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany("UserAssessmentIAIs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentPanel", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentPanels")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany("UserAssessmentPanels")
                        .HasForeignKey("UserMasterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentTracker", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.AssessmentDomain", "AssessmentDomain")
                        .WithMany("UserAssessmentTrackers")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("UserAssessmentTrackers")
                        .HasForeignKey("QuestionId");

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserAssessmentTrackers")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentDomain");

                    b.Navigation("Question");

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserMaster", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserMasters")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponse", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Answer", "Answer")
                        .WithMany("UserResponses")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserResponses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Question", "Question")
                        .WithMany("UserResponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserAssessment", "UserAssessment")
                        .WithMany("UserResponses")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Client");

                    b.Navigation("Question");

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponseMultipleAnswer", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Answer", "Answer")
                        .WithMany("UserResponseMultipleAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserResponse", "UserResponse")
                        .WithMany("UserResponseMultipleAnswers")
                        .HasForeignKey("UserResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("UserResponse");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MySkillTest.Domain.Entities.Client", "Client")
                        .WithMany("UserRoles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkillTest.Domain.Entities.UserMaster", "UserMaster")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Role");

                    b.Navigation("UserMaster");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Answer", b =>
                {
                    b.Navigation("UserResponseMultipleAnswers");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentDetails");

                    b.Navigation("AssessmentQuestions");

                    b.Navigation("LibraryQuestions");

                    b.Navigation("UserAssessments");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.AssessmentDomain", b =>
                {
                    b.Navigation("AssessmentDetails");

                    b.Navigation("AssessmentDomainLimitTrackers");

                    b.Navigation("AssessmentLibraries");

                    b.Navigation("Questions");

                    b.Navigation("UserAssessmentTrackers");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Client", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Roles");

                    b.Navigation("UserAssessments");

                    b.Navigation("UserMasters");

                    b.Navigation("UserResponses");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Compiler", b =>
                {
                    b.Navigation("AssessmentDomains");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Complexity", b =>
                {
                    b.Navigation("AssessmentDetails");

                    b.Navigation("AssessmentDomainLimitTrackers");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.EvidenceReport", b =>
                {
                    b.Navigation("EvidenceReportDetails");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.PrimaryDomain", b =>
                {
                    b.Navigation("AssessmentDomains");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("AssessmentQuestions");

                    b.Navigation("LibraryQuestions");

                    b.Navigation("UserAssessmentTrackers");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessment", b =>
                {
                    b.Navigation("AssessmentDomainLimitTrackers");

                    b.Navigation("EvidenceReports");

                    b.Navigation("UserAssessmentEvidenceDetails");

                    b.Navigation("UserAssessmentIAIs");

                    b.Navigation("UserAssessmentPanels");

                    b.Navigation("UserAssessmentTrackers");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserAssessmentStatu", b =>
                {
                    b.Navigation("UserAssessments");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserMaster", b =>
                {
                    b.Navigation("UserAssessmentIAIs");

                    b.Navigation("UserAssessmentPanels");

                    b.Navigation("UserAssessments");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MySkillTest.Domain.Entities.UserResponse", b =>
                {
                    b.Navigation("UserResponseMultipleAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
